--TROPIC QUAKES
SELECT * FROM earthquakes WHERE latitude BETWEEN -10 AND 10 ORDER BY mag DESC;
--ARCTIC QUAKES
SELECT * FROM earthquakes WHERE latitude BETWEEN 70 AND 90 UNION SELECT * FROM earthquakes WHERE latitude BETWEEN -90 AND -70 ORDER BY mag DESC;
--VERY DEEP QUAKES
SELECT * FROM earthquakes WHERE quakedepth BETWEEN 100 AND 1000 ORDER BY mag DESC;